import { onDocumentCreated } from "firebase-functions/v2/firestore";
import * as logger from "firebase-functions/logger";
import { defineSecret } from "firebase-functions/params";

const REGION = "asia-southeast2";
const DB_TARGET = process.env.FIRESTORE_DATABASE || "database-siyap";
const geminiApiKey = defineSecret("GEMINI_API_KEY");

export const onRepositoryItemCreated = onDocumentCreated({
    document: "repositoryItems/{itemId}",
    region: REGION,
    database: DB_TARGET,
    secrets: [geminiApiKey],
    memory: "256MiB",
    timeoutSeconds: 60
}, async (event) => {
    const snap = event.data;
    if (!snap) return;

    const item = snap.data();
    const itemId = event.params.itemId;

    // Hanya proses tipe file atau link, dan abaikan yang dibuat secara otomatis oleh sistem arsip (karena sudah diklasifikasikan/jelas)
    if (item.tipe === 'folder' || item.aiClassification || item.autoGenerated) return;

    const apiKey = geminiApiKey.value();
    if (!apiKey) {
        logger.error("API Key Gemini tidak ditemukan.");
        return;
    }

    try {
        const { getFirestore } = await import("firebase-admin/firestore");
        const db = getFirestore(DB_TARGET);
        const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent?key=${apiKey}`;

        // Prompt untuk Gemini
        const promptText = `
Anda adalah asisten cerdas untuk manajemen arsip/dokumen instansi pemerintahan (Smart Folder AI).
Tugas Anda adalah mengklasifikasikan dokumen baru berdasarkan nama filenya, dan membuat deskripsi/ringkasan yang sangat singkat (maksimal 1 kalimat).

Nama File/Dokumen: "${item.nama}"
Tipe Ekstensi File: "${item.tipe}"

Pilih salah satu Kategori Utama berikut yang paling cocok:
- Keuangan & Anggaran
- Kepegawaian & SDM
- Laporan & Evaluasi
- Surat Keputusan (SK) & Peraturan
- Surat Persuratan
- Perencanaan & Strategi
- Teknis Operasional
- Umum & Lainnya

Keluarkan dalam format JSON murni tanpa markdown:
{
  "aiClassification": "Kategori Utama",
  "aiSummary": "1 kalimat ringkasan tentang kemungkinan isi/kegunaan dokumen berdasarkan namanya"
}`;

        const payload = {
            contents: [{ parts: [{ text: promptText }] }],
            generationConfig: {
                temperature: 0.1, // Deterministic
                responseMimeType: "application/json",
                responseSchema: {
                    type: "OBJECT",
                    properties: { 
                        aiClassification: { type: "STRING" },
                        aiSummary: { type: "STRING" }
                    },
                    required: ["aiClassification", "aiSummary"]
                }
            }
        };

        const response = await fetch(apiUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });

        if (response.ok) {
            const data = await response.json();
            const textResult = data.candidates?.[0]?.content?.parts?.[0]?.text;
            if (textResult) {
                const parsed = JSON.parse(textResult);
                if (parsed.aiClassification && parsed.aiSummary) {
                    await db.collection("repositoryItems").doc(itemId).update({
                        aiClassification: parsed.aiClassification,
                        aiSummary: parsed.aiSummary
                    });
                    logger.info(`Berhasil melakukan klasifikasi AI untuk item ${itemId}: ${parsed.aiClassification}`);
                }
            }
        } else {
            logger.error("AI Repository Error:", await response.text());
        }

    } catch (error) {
        logger.error(`Error pada onRepositoryItemCreated untuk item ${itemId}:`, error);
    }
});
