import { onDocumentUpdated } from "firebase-functions/v2/firestore";
import * as admin from "firebase-admin";
import * as logger from "firebase-functions/logger";
import { db, REGION } from "../config/firebase";
import { Surat } from "../types";

const DB_TARGET = process.env.FIRESTORE_DATABASE || "database-siyap";

export const onSuratDiarsipkan = onDocumentUpdated(
    {document: "surat/{suratId}", region: REGION, database: DB_TARGET},
    async (event) => {
        const beforeData = event.data?.before.data() as Surat;
        const afterData = event.data?.after.data() as Surat;
        const suratId = event.params.suratId;

        // Cek jika status berubah menjadi "Diarsipkan"
        if (beforeData.statusPenyelesaian !== "Diarsipkan" && afterData.statusPenyelesaian === "Diarsipkan") {
            logger.log(`Surat ${suratId} diarsipkan. Memulai Auto-Archive ke Repository...`);
            
            const opdId = afterData.opdId;
            if (!opdId) {
                logger.warn(`Surat ${suratId} tidak memiliki opdId.`);
                return;
            }
            
            // Ambil waktu persuratan
            const createdAt: admin.firestore.Timestamp = (afterData as any).tanggalSuratDiterima || (afterData as any).tanggalSuratMasuk || admin.firestore.Timestamp.now();
            const dateObj = createdAt.toDate();
            const yearStr = dateObj.getFullYear().toString();
            // const monthStr = (dateObj.getMonth() + 1).toString().padStart(2, '0');

            // 1. Cari atau buat folder "Arsip Surat Masuk" di root
            let arsipRootId = "";
            const rootQuery = await db.collection("repositoryItems")
                .where("opdId", "==", opdId)
                .where("parentId", "==", null)
                .where("nama", "==", "Arsip Surat Masuk")
                .where("tipe", "==", "folder")
                .limit(1).get();
                
            if (rootQuery.empty) {
                const newRootRef = await db.collection("repositoryItems").add({
                    nama: "Arsip Surat Masuk",
                    tipe: "folder",
                    parentId: null,
                    opdId: opdId,
                    createdBy: "system",
                    createdAt: admin.firestore.FieldValue.serverTimestamp(),
                    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
                    visibility: "opd",
                    autoGenerated: true,
                });
                arsipRootId = newRootRef.id;
            } else {
                arsipRootId = rootQuery.docs[0].id;
            }

            // 2. Cari atau buat folder Tahun (misal: "2026")
            let yearFolderId = "";
            const yearQuery = await db.collection("repositoryItems")
                .where("opdId", "==", opdId)
                .where("parentId", "==", arsipRootId)
                .where("nama", "==", yearStr)
                .where("tipe", "==", "folder")
                .limit(1).get();
            
            if (yearQuery.empty) {
                const newYearRef = await db.collection("repositoryItems").add({
                    nama: yearStr,
                    tipe: "folder",
                    parentId: arsipRootId,
                    opdId: opdId,
                    createdBy: "system",
                    createdAt: admin.firestore.FieldValue.serverTimestamp(),
                    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
                    visibility: "opd",
                    autoGenerated: true,
                });
                yearFolderId = newYearRef.id;
            } else {
                yearFolderId = yearQuery.docs[0].id;
            }

            // 3. Cari atau buat folder Bulan (misal: "Agustus")
            const monthNames = ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"];
            const monthName = monthNames[dateObj.getMonth()];
            let monthFolderId = "";
            const monthQuery = await db.collection("repositoryItems")
                .where("opdId", "==", opdId)
                .where("parentId", "==", yearFolderId)
                .where("nama", "==", monthName)
                .where("tipe", "==", "folder")
                .limit(1).get();
            
            if (monthQuery.empty) {
                const newMonthRef = await db.collection("repositoryItems").add({
                    nama: monthName,
                    tipe: "folder",
                    parentId: yearFolderId,
                    opdId: opdId,
                    createdBy: "system",
                    createdAt: admin.firestore.FieldValue.serverTimestamp(),
                    updatedAt: admin.firestore.FieldValue.serverTimestamp(),
                    visibility: "opd",
                    autoGenerated: true,
                });
                monthFolderId = newMonthRef.id;
            } else {
                monthFolderId = monthQuery.docs[0].id;
            }

            // 4. Buat item Repository Link yang mengarah ke detail surat
            await db.collection("repositoryItems").add({
                nama: afterData.perihal || "Tanpa Perihal",
                tipe: "link",
                parentId: monthFolderId,
                opdId: opdId,
                createdBy: "system",
                createdAt: admin.firestore.FieldValue.serverTimestamp(),
                updatedAt: admin.firestore.FieldValue.serverTimestamp(),
                visibility: "opd",
                url: `/dashboard/surat-masuk/${suratId}`,
                deskripsi: `Pengirim: ${afterData.pengirim || "Tidak Diketahui"}`,
                autoGenerated: true,
                linkedToType: "surat",
                linkedToId: suratId,
                tags: ["Arsip Otomatis", "Surat Masuk", yearStr]
            });

            logger.log(`Auto-Archive berhasil untuk Surat ${suratId}`);
        }
    }
);
